version: '3'
services:
  wic-backend: 
    image: wic-backend:latest
    ports:
      - '8080:8080'
    networks:
      - wic-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - wic-app
    volumes:
      - mongo-data:/data/db
networks:
  wic-app: 
    driver: bridge
volumes:
  mongo-data:
    driver: local